// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9s7pZoC6Y8DQDW7af99nKrUinvo0ZWco',
    appId: '1:211754270472:android:126593b1ff75077b28b6bd',
    messagingSenderId: '211754270472',
    projectId: 'mediaorganizer-60e27',
    storageBucket: 'mediaorganizer-60e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6Ki5SHTjDNvVD6NR61ugakddpQWjRaA',
    appId: '1:211754270472:ios:60ff38922944c10a28b6bd',
    messagingSenderId: '211754270472',
    projectId: 'mediaorganizer-60e27',
    storageBucket: 'mediaorganizer-60e27.firebasestorage.app',
    androidClientId: '211754270472-se1ohkvkmcmeqfdn058s86e1loedppl9.apps.googleusercontent.com',
    iosClientId: '211754270472-70cin5uftq7qrt4us74mrni43il11odh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaorganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhlM4lpf8qmNpU0ORJP9llLuaODKnc2n4',
    appId: '1:211754270472:web:c8486490dcc0bfac28b6bd',
    messagingSenderId: '211754270472',
    projectId: 'mediaorganizer-60e27',
    authDomain: 'mediaorganizer-60e27.firebaseapp.com',
    storageBucket: 'mediaorganizer-60e27.firebasestorage.app',
  );
}
